version: '3.9'

# uffizzi integration
x-uffizzi:
  ingress:
    service: typebot-viewer
    port: 3001

services:

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=PublicTypebot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=typebot
      - PGDATA=/tmp
    deploy:
          resources:
            limits:
              memory: 1000M
 
  typebot-builder:
    image: "${TYPEBOT_BUILDER_IMAGE}"
    ports:
      - '3000:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@localhost:5432/PublicTypebot
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_VIEWER_URL=http://localhost:3001
      - ENCRYPTION_SECRET=SgVkYp2s5v8y/B?E(H+MbQeThWmZq4t6
      - ADMIN_EMAIL=me@email.com
      - GITHUB_CLIENT_ID=37a279454d016598c2df
      - GITHUB_CLIENT_SECRET=4b288a509352b591cd4478e3ac901668b2f8ed03
    deploy:
          resources:
            limits:
              memory: 1000M

  typebot-viewer:
    image: "${TYPEBOT_VIEWER_IMAGE}"
    ports:
      - '3001:3001'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@localhost:5432/PublicTypebot
      - NEXT_PUBLIC_VIEWER_URL=http://localhost:3001
      - ENCRYPTION_SECRET=SgVkYp2s5v8y/B?E(H+MbQeThWmZq4t6
    deploy:
          resources:
            limits:
              memory: 1000M
volumes:
  postgres_data:
